twitter/rpc-perf

.travis.yml
- create .travis.yml osx/linux across stable/beta/nightly rust
=> adding travis support

src/main.rs
These changes are not really important but stuck out when I started reading through the source.
=> Remove a couple `Option.unwrap` calls in main.rs

src/main.rs
- switch to `if let` syntax for more options
- value checking for some options
- rustfmt
=> improve option parsing

deps/parser/src/redis.rs
The parser would never had parsed a null array because the check
looked for the entire line ("*-1\r\n"), not just the length ("-1").
Added a test for the null Array case.
Cleaned up bits at the beginning to not make intermediate collections.
Reformatted the `parse` function to be expression oriented as opposed
to statement oriented.
=> Fix but in redis parser and clean up a bit.

Cargo.lock, deps/parser/Cargo.toml
- #26 is merged, increment parser version
=> parser 0.1.3

Cargo.lock, Cargo.toml, src/main.rs
- use heatmap for storing the trace
- allow png waterfall generation
=> heatmap and waterfall

Cargo.toml, src/main.rs
- sort alphabetically in Cargo.toml
- sort alphabetically in src/main.rs
=> dependency ordering

Cargo.lock, lib/parser/Cargo.toml, lib/parser/src/lib.rs, lib/parser/src/thrift.rs, lib/request/Cargo.toml, lib/request/src/lib.rs, lib/request/src/thrift.rs, lib/workload/src/lib.rs, src/connection.rs, src/main.rs
- add basic thrift framed transport + binary protocol support
- bugfix: incomplete response buffer was lost #32
- add decimals to rates
=> thrift framed binary ping

lib/parser/src/thrift.rs, lib/request/src/thrift.rs
Also ran rustfmt lib/request/src/thrift.rs
I hope you don't mind that I've taken an interest in your library: I'm using it to learn rust and pretty much all the protocols you're targeting. If these PRs are bothersome please feel free to let me know.
=> Use more efficient Vec methods for thrift protocol

Cargo.lock, Cargo.toml, lib/workload/Cargo.toml
=> cargo update

src/config.rs, src/logger.rs, src/main.rs, src/net.rs
- fixing 30 clippy warnings across 4 files
=> fix clippy warnings

Cargo.lock, lib/parser/Cargo.toml, lib/parser/src/echo.rs, lib/parser/src/memcache.rs, lib/parser/src/ping.rs, lib/parser/src/redis.rs
- fix clippy warnings in the parser lib
=> parser: fix clippy warnings

Cargo.lock, lib/request/Cargo.toml, lib/request/src/memcache.rs, lib/request/src/ping.rs, lib/request/src/redis.rs, lib/request/src/thrift.rs
- fix clippy warnings in the request lib
=> request: fix clippy warnings

src/config.rs, src/main.rs
- basic support for testing multiple servers
=> multiserver support

Cargo.lock, Cargo.toml, lib/workload/Cargo.toml
- heatmap 0.1.7
- histogram 0.3.6
- shuteye 0.1.1
- waterfall 0.1.4
=> dependency updates

Cargo.lock, lib/workload/Cargo.toml
- update ratelimit to 0.2.4
- fixes #46
=> ratelimit fix

Cargo.lock, Cargo.toml, lib/workload/Cargo.toml
- use path spec for sub-crates so that development is easy again
=> make development easy again

src/main.rs
- start() now takes a ClientConfig
=> factor client config out to a new struct

src/logger.rs
- #61 left trace logging enabled
- this fixes #65
=> revert trace logging

configs/thrift_calc.toml, lib/workload/src/lib.rs, src/config.rs, src/main.rs
Break down the extraction process.
Assert structure better.
Avoid panicing on bad config.
=> Clean up some of the config logic

lib/workload/src/lib.rs
This PR shouldn't change behavior or performance in any material way.
Nested match statements cause a lot of indentation. For low cardinality
matches an if/else tree is more space friendly especially when there is
no need for the terminating else statement.
Ran rustfmt on workload/src/lib.rs which removed many brace enclosed
blocks that contained a single statement.
=> Reduce indent by using if/else on low cardenality matches

LICENSE
=> Add into to LICENSE

src/config.rs, src/logger.rs, src/main.rs, src/stats.rs
- move statistics into stats.rs
- remove module filter in logger
- handle non-existent config better
- config override methods
=> reduce complexity of main

src/main.rs
- move workload launching out into `launch_workloads()`
- config loading to `load_config()`
- cleanup ClientConfig {} declaration
- rustfmt
=> simplify main

Cargo.toml, lib/request/Cargo.toml, lib/request/src/echo.rs, lib/request/src/lib.rs, lib/request/src/memcache.rs, lib/request/src/ping.rs, lib/request/src/redis.rs, lib/request/src/thrift.rs, lib/request/src/workload.rs
- adding benchmark tests to request generator
- with nightly rust, run in lib/request: cargo bench --features unstable
=> rpcperf_request: add benchmarks

.travis.yml
- add matrix entries for benchmarking request crate
=> make travis run bench for request

Cargo.toml
- bump version to 1.0.0-nightly.20160420
=> bump nightly version

lib/thrift/src/buffer.rs
=> impl Default for Buffer

Cargo.lock, Cargo.toml, src/connection.rs, src/main.rs, src/stats.rs
- implement HTTP accessible stats for rpc-perf
- counters and gauges
- histogram exposed on /histogram
- json output on /vars.json
- human readable output on /vars
=> basic http stats

lib/cfgtypes/src/lib.rs, lib/echo/src/lib.rs, lib/memcache/src/lib.rs, lib/ping/src/lib.rs, lib/redis/src/lib.rs, lib/redis/src/parse.rs, lib/request/src/config.rs, lib/thrift/src/config.rs, src/client.rs, src/connection.rs, src/main.rs, src/stats.rs
- ran cargo-rustfmt against the whole codebase correcting many formatting errors
=> rustfmt all the things

Cargo.lock, Cargo.toml, src/main.rs, src/stats.rs
- updating to the newest version of histogram, heatmap, and waterfall
=> update histogram, heatmap, waterfall

Cargo.lock, Cargo.toml
- bump heatmap/waterfall to 0.3.x
=> rpc-perf nightly.20160613

.travis.yml
- adding coverage of the --release build profile
=> add travis release coverage

.travis.yml, Cargo.lock, Cargo.toml, README.md, src/client.rs, src/connection.rs, src/main.rs, src/stats.rs
- use the `tic` crate for stats
- add `asm` feature to enable rdtsc timing on intel x86_64
- expand travis coverage for new feature
- readme changes for new feature
=> use tic for stats

Cargo.lock, Cargo.toml, src/client.rs
* update tic to 0.1.0
* version bump
=> Update tic and bump version

Cargo.toml, src/client.rs
- replace magic values with consts and functions
- more helper functions to reduce complexity
=> cleanup client

src/client.rs, src/main.rs
- adding a connect timeout with same value as request timeout
=> add connect timeout

Cargo.lock, Cargo.toml, lib/cfgtypes/src/lib.rs, lib/cfgtypes/src/tools.rs, lib/common/Cargo.toml, lib/common/src/lib.rs, lib/echo/src/lib.rs, lib/memcache/src/lib.rs, lib/ping/src/lib.rs, lib/ping/src/parse.rs, lib/redis/src/lib.rs, lib/redis/src/parse.rs, lib/request/src/config.rs, lib/request/src/lib.rs, lib/request/src/workload.rs, lib/thrift/src/buffer.rs, lib/thrift/src/config.rs, lib/thrift/src/gen.rs, lib/thrift/src/parse.rs, lib/thrift/src/tests.rs, rustfmt.toml, src/client.rs, src/connection.rs, src/logger.rs, src/main.rs, src/stats.rs, tests/unit.rs
- adding --service option to run continuously
- clippy and formatting fixes
- waterfall and trace fixes
- move DNS resolution into client to reduce DNS queries
=> continuous run mode

src/codec/echo/gen.rs, src/codec/memcache/gen.rs, src/codec/ping/gen.rs, src/codec/redis/gen.rs, src/codec/thrift/testutil.rs
- fix dead_code and unused_import warnings for tests
- cleanup some extra whitespace
=> fix warnings

build.rs, src/cfgtypes/mod.rs, src/codec/echo/parse.rs, src/codec/memcache/gen.rs, src/codec/memcache/mod.rs, src/codec/memcache/parse.rs, src/codec/redis/mod.rs, src/codec/thrift/config.rs, src/codec/thrift/gen.rs, src/main.rs, src/request/config.rs, src/request/workload.rs
- rustfmt
- fix all clippy warnings
=> rustfmt and clippy

.travis.yml, src/codec/redis/mod.rs, src/stats.rs
- adding a run of rustfmt to the travis builds to enforce style
=> add rustfmt to travis builds

Cargo.lock, Cargo.toml
=> release rpc-perf 2.0.0

.travis.yml, Cargo.lock, Cargo.toml, src/main.rs
- this feature only works in builds from source and is broken for cargo install rpc-perf
=> remove git versioning

Cargo.lock, Cargo.toml, configs/default.toml, configs/hotkey_hit.toml, configs/mixed_workload.toml
- update log 0.3.6 -> 0.3.7
- update mio 0.6.6 -> 0.6.7
- update tic 0.1.10 -> 0.1.11
- remove clippy optional dependency
=> updating deps

Cargo.lock, Cargo.toml, src/client.rs, src/common/mod.rs, src/connection.rs, src/main.rs, src/request/workload.rs, src/stats.rs
- updating to tic 0.2.0
- workload cpu usage reduction
- code formatting and cleanup
- halt! macro
=> update tic 0.2.0

benches/bench.rs, configs/large_payload.toml, src/client/config.rs, src/client/connection.rs, src/client/mod.rs, src/common/mod.rs, src/main.rs, src/request/config.rs, src/request/mod.rs, src/stats.rs
- allow setting of buffer size
- remove reconnect on response error
=> feature: buffer size

.gitignore, .travis.yml, src/codec/memcache/mod.rs, src/codec/redis/mod.rs, src/codec/thrift/buffer.rs, src/request/workload.rs
- formatting changes in rustfmt 0.8.6
- improve travis config
=> fix: rustfmt

Cargo.lock, Cargo.toml, src/cfgtypes/mod.rs, src/client/config.rs, src/client/mod.rs, src/codec/thrift/config.rs, src/codec/thrift/gen.rs, src/main.rs, src/request/config.rs, src/request/workload.rs
- cleanup some code style and formatting
- dependency updates which do not require significant code changes: byteorder, crc, getopts, mio, rand, ratelimit, shuteye, tic, time, toml
=> refactor: style and dependency updates

src/codec/redis_inline/gen.rs, src/codec/redis_inline/mod.rs
This is a small change to add an optional 3rd parameter to redis's set command to set the ttl option.
=> Add ttl option for Redis inline set command

src/cfgtypes/mod.rs
sorry about the bug :( i guess i had forgotten to test this with num == 0.
=> fix input checking bug for num

Cargo.lock, Cargo.toml, configs/eval.toml, src/codec/redis_inline/gen.rs, src/codec/redis_inline/mod.rs, src/codec/redis_resp/gen.rs, src/codec/redis_resp/mod.rs, src/main.rs
Follow-up on https://github.com/twitter/rpc-perf/pull/172, but I managed to finish implementing Eval and Evalsha. Evalsha actually preloads the script on the redis instance to make sure it's warm.
I've incorporated changes from the previous PR in addition of a few changes.
Let me know how this looks! 🙏
=> Add Eval and Evalsha

Cargo.toml
* bump version to release version 2.1.0
=> prepare release: 2.1.0

Cargo.lock, Cargo.toml, rpc-perf/src/stats/mod.rs, waterfall/CHANGELOG.md, waterfall/Cargo.toml, waterfall/examples/simulator.rs, waterfall/src/lib.rs
* better data handling to avoid crash when histogram is empty
=> bugfix: fix waterfall crash on empty histogram

datastructures/src/histogram/bucket.rs, metrics/src/channel.rs
* remove trace-level messages for histogram bucket initialization
* remove trace-level messages for metrics::channel
=> logging: remove some trace-level messages

.travis.yml, codec/src/redis/mod.rs, rpc-perf/src/codec/memcache.rs, rpc-perf/src/codec/mod.rs, rpc-perf/src/config/mod.rs
* fix clippy run in CI
* fixes for clippy lints
* rustfmt
=> clippy and rustfmt

rpc-perf/src/config/general.rs, rpc-perf/src/config/mod.rs
* enables serde deny_unknown_fields
* errors out if unknown fields present in config
* fixes #192
=> config: validate config and report errors

waterfall/src/lib.rs
* removes unused variable in waterfall
=> remove unused variable

.travis.yml, Cargo.lock, bench.sh, codec/Cargo.toml, codec/benches/echo.rs, codec/benches/memcache.rs, codec/benches/ping.rs, codec/benches/redis.rs, waterfall/src/lib.rs
* adds microbenchmarks to the codec crate
=> codec: microbenchmarks

Cargo.lock, datastructures/src/histogram/mod.rs
Improves the performance of the histogram index calculation by
utilizing some already calculated values
=> Histogram performance improvement

Cargo.lock, buffer/Cargo.toml, codec/Cargo.toml, rpc-perf/Cargo.toml, waterfall/Cargo.toml
Pull-in non-breaking updates to dependencies
=> Minor dependency updates

Cargo.lock, atomics/Cargo.toml, atomics/src/atomic_counter/atomic_i16.rs, atomics/src/atomic_counter/atomic_i32.rs, atomics/src/atomic_counter/atomic_i64.rs, atomics/src/atomic_counter/atomic_i8.rs, atomics/src/atomic_counter/atomic_isize.rs, atomics/src/atomic_counter/atomic_u16.rs, atomics/src/atomic_counter/atomic_u32.rs, atomics/src/atomic_counter/atomic_u64.rs, atomics/src/atomic_counter/atomic_u8.rs, atomics/src/atomic_counter/atomic_usize.rs, atomics/src/atomic_counter/mod.rs, atomics/src/atomic_primitive/atomic_bool.rs, atomics/src/atomic_primitive/atomic_i16.rs, atomics/src/atomic_primitive/atomic_i32.rs, atomics/src/atomic_primitive/atomic_i64.rs, atomics/src/atomic_primitive/atomic_i8.rs, atomics/src/atomic_primitive/atomic_isize.rs, atomics/src/atomic_primitive/atomic_ptr.rs, atomics/src/atomic_primitive/atomic_u16.rs, atomics/src/atomic_primitive/atomic_u32.rs, atomics/src/atomic_primitive/atomic_u64.rs, atomics/src/atomic_primitive/atomic_u8.rs, atomics/src/atomic_primitive/atomic_usize.rs, atomics/src/atomic_primitive/mod.rs, atomics/src/lib.rs
Adds serde deserializer for all types except `AtomicPtr<T>`
=> atomics: serde deserializer

Cargo.lock
Updates build dependencies using `cargo update`
=> build: update dependencies

Cargo.lock, rpc-perf/Cargo.toml, rpc-perf/configs/pelikan_rds.toml, rpc-perf/configs/redis.toml, rpc-perf/src/codec/memcache.rs, rpc-perf/src/codec/mod.rs, rpc-perf/src/codec/pelikan_rds.rs, rpc-perf/src/codec/redis.rs, rpc-perf/src/config/general.rs, rpc-perf/src/config/mod.rs, rpc-perf/src/main.rs
Adds support to load-test Pelikan RDS (Rich Data Server)
=> rpc-perf: add Pelikan RDS support

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
Adds GitHub templates for Issues and PRs
=> adds GitHub templates

datastructures/src/buffer/mod.rs, datastructures/src/counter/counter_primitive/mod.rs, datastructures/src/counter/mod.rs, datastructures/src/heatmap/mod.rs, datastructures/src/histogram/mod.rs
Problem
The datastructures crate was lacking in documentation
Solution
Adds documentation for the datastructures crate to improve docs coverage
Result
Better documentation
=> datastructures: improve documentation

datastructures/src/buffer/mod.rs, datastructures/src/heatmap/mod.rs, datastructures/src/histogram/mod.rs
Problem
Use declaration style is inconsistent
Solution
Improve use declaration organization
=> datastructures: use declarations

metrics/examples/benchmarks.rs, metrics/src/channel.rs, metrics/src/lib.rs, metrics/src/point.rs, metrics/src/recorder.rs
=> metrics: use short license headers

timer/src/lib.rs
=> timer: use short license headers

waterfall/examples/simulator.rs, waterfall/src/lib.rs
=> waterfall: use short license headers

timer/src/lib.rs
Adds documentation for the timer crate.
=> timer: add rustdoc

waterfall/src/lib.rs
Adds rustdoc for waterfall crate
=> waterfall: add rustdoc

metrics/src/channel.rs, metrics/src/lib.rs, metrics/src/point.rs, metrics/src/recorder.rs
Adds basic rustdocs for the metrics crate
=> metrics: add rustdocs

atomics/src/atomic_primitive/atomic_f32.rs, atomics/src/atomic_primitive/atomic_f64.rs, atomics/src/atomic_primitive/mod.rs
Adds floating point atomics through bit conversion to atomic
integer types.
=> atomics: add floating point atomics

.travis.yml, datastructures/src/heatmap/mod.rs, ratelimiter/examples/blastoff.rs, ratelimiter/src/lib.rs
Fixes the travis ci config for rustfmt to modernize it. Fixes any
pre-existing formatting issues
=> rustfmt: fix travis config and formatting issues

.travis.yml, atomics/src/lib.rs, buffer/src/lib.rs, codec/src/lib.rs, codec/src/pelikan_rds/mod.rs, codec/src/redis/mod.rs, codec/src/thrift/cache.rs, codec/src/thrift/mod.rs, datastructures/src/lib.rs, logger/src/lib.rs, metrics/src/lib.rs, ratelimiter/src/lib.rs, rpc-perf/configs/thrift_cache_hash.toml, rpc-perf/configs/thrift_cache_list.toml, rpc-perf/src/codec/mod.rs, rpc-perf/src/codec/thrift_cache.rs, rpc-perf/src/config/general.rs, rpc-perf/src/config/mod.rs, rpc-perf/src/main.rs
Adds support for a basic cache service over Thrift protocol.
=> add support for ThriftCache

Cargo.lock
Updates thirdparty dependencies to pull in relevant bugfixes
=> update thirdparty dependencies

rpc-perf/src/codec/thrift_cache.rs
Completing a TODO to have a start and stop value for lrange in cache thrift
=> Use items for lrange end

datastructures/src/histogram/mod.rs
=> cleanup debug prints

Cargo.lock, rpc-perf/Cargo.toml
Update thirdparty dependencies to pull in any bugfixes
=> update dependency versions for bugfixes

.github/workflows/cargo.yml
Adding some basic CI through github workflows
=> add github workflow to run cargo

.github/workflows/cargo.yml, build/ci.sh
Fixes an incorrect entry for the clippy step of the workflow
=> fix workflow

Cargo.lock
Updates dependencies to pull-in any bugfixes
=> update dependencies to latest version

Cargo.lock, rpc-perf/Cargo.toml, rpc-perf/src/client/tls_client.rs
Updates rustls to the latest version
=> rpc-perf: update rustls

Cargo.lock, rpc-perf/src/stats/mod.rs
Fixes incorrect percentile stats on standard out.
Changes the waterfall palette to 'ironbow'
=> change waterfall palette, fix percentile stats

.github/workflows/cargo.yml, rpc-perf/src/stats/snapshot.rs
Invalid json exposition. Fix json and add a ci test
=> fix json exposition

Cargo.lock, buffer/Cargo.toml, buffer/src/lib.rs, codec/Cargo.toml, codec/src/echo/mod.rs, codec/src/memcache/mod.rs, codec/src/pelikan_rds/mod.rs, codec/src/ping/mod.rs, codec/src/redis/mod.rs, rpc-perf/Cargo.toml
Updates bytes library to 0.6.0 and makes necessary changes to use
the newer library.
=> update bytes to 0.6.0

.github/workflows/cargo.yml
Borrow the CI improvements from rustcommon for this repo.
=> ci: performance improvements

.github/workflows/cargo.yml
Integrate the CI improvements from the master branch
=> ci: integrate changes to ci from master branch

.github/workflows/cargo.yml, configs/memcache.toml, configs/pelikan.toml
Integrates CI changes from master branch.
=> ci: integrate CI changes from master branch

LICENSE
Integrate #332 into the 4.0.0-alpha feature branch.
=> integrate #332 into feature branch

src/admin.rs, src/lib.rs, src/worker.rs
Adds an admin endpoint to adjust the reconnect ratelimit at
runtime.
=> add support for adjustable reconnect ratelimit

Cargo.lock, Cargo.toml
Replace wildcard versions with specific version numbers.
=> specify dependency versions

Cargo.lock, Cargo.toml, src/codec/echo.rs
=> update crc crate to 2.1.0

.github/workflows/cargo.yml, Cargo.lock, Cargo.toml, configs/memcache.toml, src/main.rs
Adds a custom panic hook to terminate the program if any thread
panics.
=> add custom panic hook

src/config_file.rs, src/replay.rs, src/worker.rs
=> fix ssl cert loading

.github/workflows/cargo.yml, Cargo.lock, Cargo.toml, src/lib.rs, src/metrics.rs, src/replay.rs, src/session/buffer.rs, src/session/mod.rs, src/time.rs, src/worker.rs
Updates rustcommon and boringssl dependencies
=> update rustcommon and boringssl dependencies

.github/workflows/cargo.yml, src/session/mod.rs, src/worker.rs
Adds a smoketest which uses Pelikan Segcache w/ TLS
=> ci: add smoketest w/ TLS

.github/workflows/cargo.yml, configs/pelikan.toml, src/config_file.rs, src/metrics.rs, src/session/mod.rs, src/session/stream.rs, src/worker.rs
=> Session cache

Cargo.lock, Cargo.toml
Increment version number for release 3.2.0
=> prepare for release 3.2.0

src/config.rs, src/lib.rs, src/main.rs
Adds help and version info to rpc-perf binary
=> docs: add help for rpc-perf

Cargo.lock, Cargo.toml
Updates rustcommon dependencies to ff5ca96
=> update rustcommon to ff5ca96

README.md
Add missing links for license badge
=> fix license badge

Cargo.toml
=> upgrade to Rust 2021 edition

Cargo.lock, Cargo.toml, src/admin.rs, src/metrics.rs
Updates the metrics library and adds the new metric description
annotations for each metric. Adds corresponding descriptions into
the prometheus/opentelemetry exposition format.
=> feature: add metric descriptions

configs/memcache.toml, configs/memcache_zookeeper.toml, configs/pelikan.toml, configs/redis.toml, configs/redis_resp.toml, configs/thrift_cache_hash.toml, configs/thrift_cache_list.toml, src/config_file.rs, src/macros.rs, src/session/mod.rs, src/worker.rs
Adds support for pipelining multiple requests into a single transmission.
=> add support for pipelining

src/codec/redis.rs
Adds support for pipelined commands for redis by making the
necessary changes to the response parser.
=> support pipelined commands for redis

src/codec/redis.rs
Fix redis bulk string parser bug introduced in #370
=> fix: redis bulk string parser

configs/memcache.toml, configs/memcache_zookeeper.toml, configs/pelikan.toml, configs/ping.toml, configs/redis.toml, configs/redis_resp.toml, configs/thrift_cache_hash.toml, configs/thrift_cache_list.toml, src/admin.rs, src/config.rs, src/config_file.rs, src/lib.rs, src/session/mod.rs
Improves the logging for the rpc-perf binary by adding a new `debug` section to the config which allows the user to specify the log level.
=> feat: improve logging

Cargo.lock, Cargo.toml, configs/memcache.toml, configs/memcache_zookeeper.toml, configs/pelikan.toml, configs/ping.toml, configs/redis.toml, configs/redis_resp.toml, configs/thrift_cache_hash.toml, configs/thrift_cache_list.toml, src/admin.rs, src/config.rs, src/config_file.rs, src/lib.rs, src/worker.rs
Waterfall plotting has been missing in the current version, this
change adds this feature back.
=> waterfall plotting

configs/memcache.toml, configs/memcache_zookeeper.toml, configs/pelikan.toml, configs/ping.toml, configs/redis.toml, configs/redis_resp.toml, configs/thrift_cache_hash.toml, configs/thrift_cache_list.toml, src/config_file.rs, src/lib.rs
Adds new configuration option to change waterfall time axis resolution.
=> allow configuration of waterfall resolution
