twitter/rpc-perf

- lib/parser/src/echo.rs
- lib/parser/src/memcache.rs
- lib/parser/src/ping.rs
- lib/parser/src/redis.rs
- lib/parser/src/thrift.rs
- src/connection.rs
The actual parsing process doesn't need a unique copy of the buffer so it can actually be shared safely. Places that required a moved Vec<u8> can now take a &[u8] and places that required a moved String now take a &str, all of which are just views of the ByteBuf contents.
> Parsing does dramatically less copying

- lib/parser/src/thrift.rs
- lib/request/src/thrift.rs
Refactored the thrift request lib to follow the builder pattern. This should make it more flexible short-term for supporting more complex requests. This change also removes the right-shift of the buffer when framing the request
> thrift request refactoring

- Cargo.lock
- configs/default.toml
- configs/hotkey_hit.toml
- configs/mixed_workload.toml
- lib/request/src/echo.rs
- lib/workload/Cargo.toml
- lib/workload/src/lib.rs
- src/config.rs
- src/main.rs
- breaking: removes cli workload support
- adds parameters as part of workload spec
- allows for random key / value geneneration - fixes #41
- extend config to allow specifying parameters for workload
- update example configs with new format
- bump workload to 0.2.0
> workload refactoring

- Cargo.lock
- Cargo.toml
- lib/parser/Cargo.toml
- lib/parser/README.md
- lib/parser/src/lib.rs
- lib/request/Cargo.toml
- lib/request/README.md
- lib/request/src/echo.rs
- lib/request/src/lib.rs
- lib/request/src/memcache.rs
- lib/request/src/ping.rs
- lib/request/src/redis.rs
- lib/request/src/thrift.rs
- lib/workload/Cargo.toml
- lib/workload/README.md
- lib/workload/src/lib.rs
- src/config.rs
- src/connection.rs
- src/main.rs
- tests/unit.rs
- indicate nightly date for rpc-perf
- fix license strings
- add homepage and repository metadata
- mpmc 0.1.2 from crates.io
- prefix parser, request, workload, with rpcperf_
- bump parser to 1.0.0
- bump request to 1.0.0
- bump workload to 1.0.0
> prepare for publish on crates.io

- configs/thrift_calc.toml
- lib/request/src/thrift.rs
- lib/workload/src/lib.rs
- src/client.rs
- src/config.rs
- src/logger.rs
- src/main.rs
- add generic thrift support to rpc-perf
- rpcperf: config file changes to support
- rpcperf_request: support generic thrift requests
- rpcperf_workload: major changes
- travis: mark osx can fail, enable fast finsh
> generic thrift support

- lib/request/src/thrift.rs
Closes #63
Cleans up some manual buffer management.
> thrift::buffer write methods use WriteBytesExt

- lib/workload/src/lib.rs
- this change removes an unnecessary clone when pushing to the work queue
> workload: unnecessary clone()

- Cargo.lock
- Cargo.toml
- lib/request/Cargo.toml
- lib/workload/Cargo.toml
- request -> 1.1.0 for generic thrift
- workload -> 2.0.0 for breaking changes to support generic thrift
- rpc-perf -> 1.0.0-nightly.20160404
- misc dep updates
> version bumps

- src/main.rs
- fix #74
- add --version flag to cmdline options
- move version logging message up before potential exits
> add version flag

- lib/memcache/src/gen.rs
- don't repeat protocol name in the benchmark test
> improve benchmark test naming

- Cargo.lock
- Cargo.toml
- lib/request/Cargo.toml
- lib/request/src/config.rs
- lib/request/src/lib.rs
- src/client.rs
- src/connection.rs
- src/logger.rs
- src/main.rs
- src/state.rs
- src/stats.rs
- typical clients offer a timeout setting for requests, as described in #97 we wish to add this feature to rpc-perf
- adding a global request timeout to the config / command line arguments
- implement a timeout handler to drop the connection and re-connect
- change to client/connection to support the new behavior
- logging now includes milliseconds to assist with debugging
> request timeout

- Cargo.lock
- Cargo.toml
- lib/request/Cargo.toml
- lib/request/src/config.rs
- lib/request/src/lib.rs
- lib/request/src/workload.rs
- src/stats.rs
- update to new versions of ratelimit and shuteye
- removes dependency on time for workload
- no measurable performance change
> update ratelimit and shuteye

- README.md
- the version on crates.io is old, remove cargo install references
- fixes #105
> install instructions fix

- Cargo.lock
- Cargo.toml
- lib/request/src/config.rs
- lib/request/src/lib.rs
- introduced a bug for option parsing, evtick is dropped and fixed at 1ms, remove from the TOML parsing
- update tic to 0.0.8 which includes fix for perceptual artifacts in the waterfall renders
> update tic and bugfix for option parsing

- configs/default.toml
- lib/redis/src/gen.rs
- lib/redis/src/lib.rs
- src/main.rs
This PR adds a `--database` option to rpc-perf, so that when initially connecting to a Redis instance you can select which database to use.
I've been using it to measure the overhead of mixing writes to different keyspaces vs. the same, db0, keyspace.
> Redis database selection

- Cargo.lock
- Cargo.toml
- lib/cfgtypes/Cargo.toml
- lib/cfgtypes/src/lib.rs
- lib/common/Cargo.toml
- lib/common/src/lib.rs
- lib/echo/Cargo.toml
- lib/echo/src/gen.rs
- lib/echo/src/lib.rs
- lib/echo/src/parse.rs
- lib/memcache/Cargo.toml
- lib/memcache/src/lib.rs
- lib/memcache/src/parse.rs
- lib/ping/Cargo.toml
- lib/ping/src/lib.rs
- lib/redis/Cargo.toml
- lib/redis/src/lib.rs
- lib/request/Cargo.toml
- lib/request/src/config.rs
- lib/request/src/lib.rs
- lib/request/src/workload.rs
- lib/thrift/Cargo.toml
- lib/thrift/src/buffer.rs
- lib/thrift/src/config.rs
- lib/thrift/src/gen.rs
- lib/thrift/src/lib.rs
- lib/thrift/src/parse.rs
- src/client.rs
- src/logger.rs
- src/main.rs
- factor out shared dependencies into new subcrate called common, this gives single touch-point for version changes and reduces likelyhood of version mismatch following cargo update
- refactor callers to use the common library
- update dependencies and use pinned versions
- extend memcache and redis command sets to cure dead code warnings
> common library for shared dependencies

- .travis.yml
- Cargo.lock
- Cargo.toml
- drop osx travis targets to improve CI times. enqueued time is approx 2 hours for osx builds, this drops total CI time to ~10 minutes.
- re-enable debug symbols in release build, this allows profiling. might not work on osx
> build improvements

- Cargo.lock
- Cargo.toml
- configs/mixed_workload.toml
- lib/cfgtypes/Cargo.toml
- lib/common/Cargo.toml
- lib/common/src/lib.rs
- lib/echo/Cargo.toml
- lib/memcache/Cargo.toml
- lib/memcache/src/lib.rs
- lib/ping/Cargo.toml
- lib/redis/Cargo.toml
- lib/redis/src/lib.rs
- lib/request/Cargo.toml
- lib/request/src/config.rs
- lib/request/src/lib.rs
- lib/request/src/workload.rs
- lib/thrift/Cargo.toml
- src/client.rs
- src/connection.rs
- src/logger.rs
- src/main.rs
- src/net.rs
- src/stats.rs
change request dispatch
- workloads push directly onto client MPSC queues
- reduces CPU consumption and threads required
cache DNS lookups
- add basic per-connection caching of DNS lookups to avoid overwhelming DNS servers under heavy timeout/reconnect
refactor stats
-  refactoring the stats so we can gather stats on internal metrics
-  breaking: some stats have changed
-  bugfix: stats library (tic) was stalling out using mio channels. updated to tic 0.1.3 which uses MPMC queue with sender batching
> change request dispatch

- Cargo.toml
- build.rs
- no longer need build.rs, as all functions handled by normal cargo build
> remove build.rs

- Cargo.toml
- exclude is no-longer needed in Cargo.toml, we should be okay with the defaults
> Cargo.toml remove exlude

- src/stats.rs
- trace file was incorrectly registered as a Waterfall interest, resulting in saving PNG waterfall instead of a trace file
> fix: trace file

- src/main.rs
- error macro used before logging is initialized
- replace error macro with println and exit with non-zero status
> bugfix: argument parsing

- .travis.yml
- fuzz/.gitignore
- fuzz/Cargo.lock
- fuzz/Cargo.toml
- fuzz/fuzzers/fuzzer_codec_echo.rs
- fuzz/fuzzers/fuzzer_codec_memcache.rs
- fuzz/fuzzers/fuzzer_codec_ping.rs
- fuzz/fuzzers/fuzzer_codec_redis.rs
- fuzz/fuzzers/fuzzer_codec_thrift.rs
- src/codec/echo/mod.rs
- src/codec/memcache/mod.rs
- src/codec/memcache/parse.rs
- src/codec/ping/mod.rs
- src/codec/ping/parse.rs
- src/codec/redis/mod.rs
- src/codec/redis/parse.rs
- src/codec/thrift/config.rs
- src/codec/thrift/parse.rs
- src/connection.rs
- src/request/config.rs
- src/request/workload.rs
- extend travis testing to provide coverage for clippy and cargo-fuzz
- currently leaving these tests as failures allowed, will make failing in future
- make the parser interfaces public to allow fuzzing
- fixes to the codecs for problems revealed in fuzzing
> testing: cargo-fuzz and clippy

- .travis.yml
- Cargo.toml
- benches/bench.rs
- src/codec/echo/gen.rs
- src/codec/memcache/gen.rs
- src/codec/memcache/mod.rs
- src/codec/ping/gen.rs
- src/codec/ping/mod.rs
- src/codec/redis/gen.rs
- src/codec/redis/mod.rs
- src/codec/redis/parse.rs
- add benches.rs to drive benchmarks across two branches
- uses cargo-benchcmp command to compare results
- fails regressions > 20%
> ci: benchmark comparison

- README.md
- direct users to rustup.rs instead of multirust
- fixes #138
> doc: rust install

- Cargo.lock
- configs/sized_dataset.toml
- src/cfgtypes/mod.rs
- src/cfgtypes/tools.rs
- src/codec/echo/mod.rs
- src/codec/memcache/mod.rs
- src/codec/redis_inline/mod.rs
- src/codec/redis_resp/mod.rs
- src/codec/thrift/config.rs
- src/codec/thrift/mod.rs
- src/codec/thrift/testutil.rs
This change adds support for randomly generated strings to be from a dataset of size n. For this to happen, random workloads will take an additional `num` parameter which specifies the data set size. For example, with `num == 1_000_000`, the random workload will generate strings from a set of 1,000,000 strings. This will be useful for performance testing caches at different levels of heap utilization. 
I didn't find any documentation on how to configure workloads, so I added the details in an example configuration. Please let me know if there is a better place for this. I am a beginner at rust, so please let me know if anything I am writing is non idiomatic/incorrect.
> add support for explicitly sized random data sets

- src/stats.rs
* fix an off-by-one error on the check to determine if the configured number of windows have been completed
* re-add the seperator between per-window stats
> fix: too many windows before exit

- codec/Cargo.toml
- datastructures/Cargo.toml
- logger/Cargo.toml
- metrics/Cargo.toml
- ratelimiter/Cargo.toml
- rpc-perf/configs/default.toml
- rpc-perf/src/config/mod.rs
- rpc-perf/src/stats/mod.rs
* change argument parsing to make `--endpoint` optional on command line
* allow CLI to override config file for endpoints
* fix a wrap-around issue with counting open connections
* default config incorrectly specifies timeouts as ms when the unit is us
> config: allow specifying endpoints in toml

- rpc-perf/src/stats/http.rs
* changes the metrics endpoint to serve machine readable json output for unknown URIs
> rpc-perf: serve machine readable stats by default

- rpc-perf/src/client/mod.rs
* if response is 0 length, count as server closed and close connection
> fix handling of empty response

- Cargo.lock
- datastructures/Cargo.toml
- datastructures/src/histogram/latched.rs
- metrics/Cargo.toml
- metrics/src/channel.rs
- metrics/src/lib.rs
* addresses histogram bug where percentile 0.0 always is 0
* addresses histogram bug where bucket width is under-reported
* addresses metrics bug where wrap-around may be improperly handled
> bugfix for histograms and metrics

- Cargo.lock
- datastructures/Cargo.toml
- datastructures/src/histogram/latched.rs
- metrics/src/lib.rs
This change fixes the histogram to cover the full range requested.
Previously, it may have truncated the range, resulting in incorrect
data for upper percentiles when nearly the full range of the histogram
was in-use.
Fixes existing tests and adds a new test to verify the correct behavior.
> bugfix: fixes histogram range

- Cargo.lock
- datastructures/Cargo.toml
- datastructures/examples/benchmarks.rs
- datastructures/ffi/cdatastructures/src/histogram.rs
- datastructures/src/histogram/circular.rs
- datastructures/src/histogram/latched.rs
- datastructures/src/histogram/mod.rs
- datastructures/src/lib.rs
- metrics/examples/benchmarks.rs
- metrics/src/lib.rs
- rpc-perf/src/stats/mod.rs
- waterfall/Cargo.toml
- waterfall/examples/simulator.rs
- waterfall/src/lib.rs
Improves the performance of the percentile operations for the
histogram datastructures by using slightly more memory to maintain
a secondary set of counts that cover wider ranges. This is used to
accelerate the totals() and percentile() functions.
Adds a new `CircularHistogram` which is like `MovingHistogram`
but uses a fixed-size circular buffer to store the sample history. It
can be beneficial to use it when you know how many samples you
wish to retain across the time window. It has faster performance
than `MovingHistogram`.
> datastructures: histogram improvements

- Cargo.lock
- timer/Cargo.toml
- timer/src/lib.rs
Adds a function to the timer to return an option representing the
next timeout if there is one. This can be useful to get the deadline
for when the next timer would fire, allowing the working thread to
sleep until the deadling.
> timer: add next_timeout()

- metrics/src/channel.rs
- metrics/src/lib.rs
- metrics/src/recorder.rs
- rpc-perf/src/main.rs
- rpc-perf/src/stats/mod.rs
Previously, clear() would just zero out the data stored in the
recorder without removing channels that have been registered.
With this change, clear() behaves like it does on a HashMap and
actually removes registered channels. The new function, zero(),
can be used to zero the data stored, without deregistering all
of the channels.
> metrics: change behavior of clear()

- metrics/src/recorder.rs
Exposes a `shrink_to_fit()` function on the `Recorder` to allow
for reducing the memory usage after metrics have been deregistered
> metrics: expose a shrink_to_fit()

- .travis.yml
Problem
Caching in TravisCI frequently results in build timeouts while fetching
and extracting the cache files.
Solution
Remove the caching
Result
Builds should run more consistently
> ci: remove cache

- atomics/src/atomic_option/mod.rs
- atomics/src/atomic_primitive/mod.rs
- atomics/src/lib.rs
Problem
Currently we don't have a thread-safe `Option` type
Solution
Adds `AtomicOption` which provides a thread-safe `Option` equivalent
> atomics: add AtomicOption type

- rpc-perf/src/codec/mod.rs
- rpc-perf/src/codec/pelikan_rds.rs
- rpc-perf/src/config/mod.rs
Problem
For pelikan_rds all `SArray.creats`s were issued for 1byte integers (u8)
instead of using the value length properly.
Solution
Add an `esize` field to the `Command` struct. Populate that directly
from the `Value::length()` and pass it directly to the codec.
Result
`SArray.create` correctly uses the value length.
> bugfix: pelikan_rds

- rpc-perf/src/client/common.rs
Problem
Request buffer is not dumped when tracing
Solution
Add trace logging for the request buffer after request encode
Result
See content of request buffer when trace level logging enabled
> add tracing to request buffer

- Cargo.lock
- atomics/Cargo.toml
- atomics/src/atomic_primitive/atomic_bool.rs
- atomics/src/atomic_primitive/atomic_i16.rs
- atomics/src/atomic_primitive/atomic_i32.rs
- atomics/src/atomic_primitive/atomic_i64.rs
- atomics/src/atomic_primitive/atomic_i8.rs
- atomics/src/atomic_primitive/atomic_isize.rs
- atomics/src/atomic_primitive/atomic_u16.rs
- atomics/src/atomic_primitive/atomic_u32.rs
- atomics/src/atomic_primitive/atomic_u64.rs
- atomics/src/atomic_primitive/atomic_u8.rs
- atomics/src/atomic_primitive/atomic_usize.rs
Problem
Atomic primitives don't implement `Serialize`
Solution
Implement serde `Serialize` for all atomic primitives
> atomics: add serializer for atomic primitives

- rpc-perf/src/session/mod.rs
- rpc-perf/src/session/stream.rs
Problem
Previously, connections wouldn't close immediately after timeout.
Instead, they would be closed when a new connection is established.
Solution
Now, when the session is marked as closed, the socket will also be
closed.
> rpc-perf: close connections earlier

- Cargo.lock
- rpc-perf/src/codec/mod.rs
- rpc-perf/src/codec/pelikan_rds.rs
- rpc-perf/src/codec/redis.rs
- rpc-perf/src/config/mod.rs
Problem
No benchmarking support for redis list commands
Solution
Adds basic support for benchmarking redis list commands: llen,
lpush, lpushx, lrange, ltrim, rpush, rpushx
> rpc-perf: add basic redis list support

- rpc-perf/src/codec/redis.rs
Problem
Instead of issuing an `ltrim`, an `lrange` was being issued
Solution
Changed code to issue an `ltrim`
> rpc-perf: bugfix redis ltrim

- rpc-perf/src/client/common.rs
- rpc-perf/src/client/mod.rs
- rpc-perf/src/codec/redis.rs
- rpc-perf/src/config/general.rs
- rpc-perf/src/config/mod.rs
- rpc-perf/src/main.rs
Problem
Existing timeout behavior is to always close a connection, or give up on
the attempt to create a connection. Often, timeouts are due to load on
the backend, not network issues. In some cases, it may be beneficial to
wait until the connection is established or request is complete, even if it
exceeds timeout values.
Solution
Adds a "soft timeout" mode. In this mode, timeouts will count as timeouts,
but instead of closing the socket, we still wait for the connection to become
established or a response to be received.
Result
It will be possible to see error rates like a client would see, while still getting
an accurate representation of server latency.
> rpc-perf: add soft-timeout mode

- bench.sh
- codec/benches/memcache.rs
- codec/benches/ping.rs
- codec/benches/redis.rs
Problem
Current codec benchmarks result in the buffer growing with each iteration
Solution
Clear buffer after each encode
Result
Buffer remains bounded in size
> codec: fix benchmarks

- rpc-perf/src/client/common.rs
- rpc-perf/src/client/mod.rs
- rpc-perf/src/client/plain_client.rs
- rpc-perf/src/client/tls_client.rs
- rpc-perf/src/main.rs
Problem
Trait objects without an explicit `dyn` are deprecated.
Solution
Fix code to include explicit `dyn`
> rpc-perf: fix warnings about explicit dyn

- codec/benches/echo.rs
- codec/benches/memcache.rs
- codec/benches/ping.rs
- codec/benches/redis.rs
- codec/src/echo/mod.rs
- codec/src/memcache/mod.rs
- codec/src/pelikan_rds/mod.rs
- codec/src/ping/mod.rs
- codec/src/redis/mod.rs
Problem
Missing license headers on the benchmarks. Using long header for
existing headers.
Solution
Add missing license headers. Switch to short header for existing
license headers.
> codec: license headers

- buffer/src/lib.rs
Problem
Using long header for existing headers.
Solution
Switch to short header for existing license headers.
> buffer: license headers

- logger/examples/demo.rs
- logger/src/lib.rs
> logger: use short license headers

- ratelimiter/examples/blastoff.rs
- ratelimiter/src/lib.rs
> ratelimiter: use short license headers

- rpc-perf/src/client/common.rs
- rpc-perf/src/client/mod.rs
- rpc-perf/src/client/plain_client.rs
- rpc-perf/src/client/tls_client.rs
- rpc-perf/src/codec/echo.rs
- rpc-perf/src/codec/memcache.rs
- rpc-perf/src/codec/mod.rs
- rpc-perf/src/codec/pelikan_rds.rs
- rpc-perf/src/codec/ping.rs
- rpc-perf/src/codec/redis.rs
- rpc-perf/src/config/general.rs
- rpc-perf/src/config/mod.rs
- rpc-perf/src/main.rs
- rpc-perf/src/session/mod.rs
- rpc-perf/src/session/plain_session.rs
- rpc-perf/src/session/stream.rs
- rpc-perf/src/session/tls_session.rs
- rpc-perf/src/stats/http.rs
- rpc-perf/src/stats/mod.rs
> rpc-perf: use short license headers

- rpc-perf/src/client/common.rs
- rpc-perf/src/client/mod.rs
- rpc-perf/src/client/plain_client.rs
- rpc-perf/src/client/tls_client.rs
- rpc-perf/src/codec/mod.rs
- rpc-perf/src/codec/redis.rs
- rpc-perf/src/config/mod.rs
- rpc-perf/src/main.rs
- rpc-perf/src/session/mod.rs
- rpc-perf/src/session/plain_session.rs
- rpc-perf/src/session/stream.rs
- rpc-perf/src/session/tls_session.rs
- rpc-perf/src/stats/http.rs
- rpc-perf/src/stats/mod.rs
Organize the use declarations based on `crate::`, `self::`, crate,
or `std`/`core` as well as by visibility
> rpc-perf: use declarations

- codec/src/pelikan_rds/mod.rs
- codec/src/redis/mod.rs
Problem
Stray `println!()` logging in Redis and PelikanRDS codecs.
Solution
Change logging to use the `trace!()` macro instead
> codec: fix logging

- atomics/src/atomic_option/mod.rs
- atomics/src/lib.rs
Adds rustdoc with examples for `AtomicOption`. Adds module-level
rustdoc for atomics.
> atomics: improve documentation

- datastructures/src/buffer/mod.rs
- datastructures/src/heatmap/mod.rs
- datastructures/src/histogram/mod.rs
- datastructures/src/lib.rs
Minor fixes for Histogram `mean()` and `mode()` to return an option
to account for when the Histogram is empty.
Improved documentation for datastructures to include examples.
> datastructures: minor fixes and improved docs

- ratelimiter/examples/blastoff.rs
- ratelimiter/src/lib.rs
Improves the doc coverage for ratelimiter. Fixes the example so
there is a pause between last loop iteration and final print.
> ratelimiter: improve docs and fix example

- atomics/src/atomic_option/mod.rs
- atomics/src/atomic_primitive/atomic_bool.rs
- atomics/src/atomic_primitive/atomic_i16.rs
- atomics/src/atomic_primitive/atomic_i32.rs
- atomics/src/atomic_primitive/atomic_i64.rs
- atomics/src/atomic_primitive/atomic_i8.rs
- atomics/src/atomic_primitive/atomic_u16.rs
- atomics/src/atomic_primitive/atomic_u32.rs
- atomics/src/atomic_primitive/atomic_u64.rs
- atomics/src/atomic_primitive/atomic_u8.rs
Fixes clippy warnings throughout the atomics crate
> atomics: fix clippy warnings

- datastructures/src/buffer/mod.rs
- datastructures/src/histogram/mod.rs
Fixes clippy warnings in the datastructures crate
> datastructures: fix clippy warnings

- Cargo.lock
- metrics/Cargo.toml
- metrics/src/metrics/mod.rs
Adds a check for the existence of a metrics channel before taking
the lock and removing it. This avoids unnecessary locking.
Fixes #262
Problem
Currently we optimistically take a lock on the metrics registry and
remove the channel. This causes unnecessary locking when the 
channel does not exist.
Solution
Adds a check for the existence of the channel before locking and trying
to remove it.
Result
Users of the library will not need to handle tracking whether a channel is
already removed if they wish to avoid the lock.
> metrics: add check before deleting channel

- codec/src/thrift/cache.rs
Fixes incorrect field IDs for append and appendx
> codec: bugfix for thrift cache

- Cargo.lock
- Cargo.toml
- metrics-core/Cargo.toml
- metrics-core/benches/benches.rs
- metrics-core/src/dyncow.rs
- metrics-core/src/error.rs
- metrics-core/src/inner.rs
- metrics-core/src/instant.rs
- metrics-core/src/lib.rs
- metrics-core/src/macros.rs
- metrics-core/src/metadata.rs
- metrics-core/src/percentile.rs
- metrics-core/src/scoped.rs
- metrics-core/src/state.rs
- metrics-core/src/submetric.rs
- metrics-core/src/traits.rs
- metrics-core/src/value.rs
Problem
Currently all our metrics are tied to a specific implementation. Instead we'd like to reduce the coupling between where metrics are recorded and where they are used. This would allow for replacing a metric with a new type transparently to end-user code. 
Solution
This PR implements a new metrics facade under `metrics-core`. It consists of
- A few different traits that individual metrics will implement based on their type. Specifically it has traits for counters, gauges, and summaries (anything that isn't a counter or gauge).
- A global trait registrar that allows a metric to be registered under a string name and then used.
- A set of macros which are used by client code to record a value under a metric named with a string.
In addition, this PR includes a limited introspection …
> Metrics facade

- rpc-perf/src/stats/mod.rs
- waterfall/examples/simulator.rs
Problem
Waterfall generation in rpc-perf was resulting in unreadable
labels.
Solution
This was due to the label width relative to the number of
buckets. This change increases the resolution of the waterfall and
makes the waterfall simulation example use parameters more in-line
with actual rpc-perf usage.
Result
Waterfalls generated in rpc-perf have readable labels
> fixes for waterfall

- atomics/src/atomic_primitive/mod.rs
- datastructures/src/ddsketch/atomic.rs
- datastructures/src/ddsketch/dense.rs
- datastructures/src/ddsketch/error.rs
- datastructures/src/ddsketch/mod.rs
- datastructures/src/lib.rs
This adds two variants of DDSketch to the datastructures crate:
- DenseDDSketch - a non thread-safe version of DDSketch
- AtomicDDSketch - a dense ddsketch using atomic counters instead that can be shared across threads
I haven't had time to write a sparse version of ddsketch that would be suitable for inclusion in rpc-perf, hopefully I'll get some time to work on this later along with versions of the moments-sketch and q-digest.
> Add DDSketch to rpc-perf

- Cargo.lock
- waterfall/Cargo.toml
- waterfall/examples/simulator.rs
- waterfall/src/lib.rs
Previously, certain distributions could result in an all black
output. This was caused by rounding issues with integer arithmetic
in calculating the weighted count for the buckets.
Adjust the weighting algorithm to use a fixed multiplier and
increase precision used for storing the weighted counts.
Additionally, alter the coloring algorithm to improve rendering of
wide distributions. Adds additional distributions to the simulator
which were used to help identify issues.
The result is a more robust waterfall rendering which handles a
wider variety of distributions.
> waterfall: fix rendering issues for some distributions

- Cargo.toml
Reduce the cargo build profiles to the minimum set of overrides for
the behaviors we want.
> simplify cargo build profiles

- .travis.yml
- atomics/src/atomic_primitive/atomic_f32.rs
- atomics/src/atomic_primitive/atomic_f64.rs
- build/ci.sh
- metrics-core/src/instant.rs
- metrics-core/src/scoped.rs
- metrics-core/src/state.rs
- rpc-perf/src/client/tls_client.rs
Previously, we had no caching used in the ci build. This change enables travis cargo cache and tries to enable/build sccache to wrap rustc.
> enable sccache in ci build

- datastructures/src/histogram/mod.rs
An issue occurs when bounded or windowed histograms have a value
larger than the max incremented or decremented. A sample was not
properly added to the queue for trimming in the future, this would
result in the datastructure accumulating a count beyond the limit
of the histogram. When enough of these samples have been seen, the
histogram would report the max value for almost all percentiles.
Added some tests that check for the expected behavior and fixed the
logic in the increment and decrement functions.
> datastructures: bugfix for moving and windowed histograms

- rpc-perf/src/codec/mod.rs
Both these commands are initialized with the wrong action. Change
the action to the correct one for each hset and ltrim
> bugfix: hset and ltrim

- .github/workflows/cargo.yml
Adds cargo audit to ci to look for rustsec advisories for
dependencies. Currently warnings will not cause errors as there are
some existing warnings. Consider making this more strict in the
future.
> add cargo audit to ci

- rpc-perf/src/admin/mod.rs
Adds newlines to the GET responses for ratelimit. This makes the
formatting nicer when using curl.
> rpc-perf: add newlines to admin GET responses

- rpc-perf/src/client/mod.rs
- rpc-perf/src/stats/mod.rs
- rpc-perf/src/stats/snapshot.rs
- rpc-perf/src/stats/stat.rs
Fixes for http metrics exposition where counter metrics were not
being displayed.
Changes latency metrics to be responses/latency/* and
connections/latency/*
> http metrics exposition fixes

- src/client/mod.rs
Bug introduced in #305 results in incorrect latency measurements
when ratelimited.
This change addresses the bug by updating the session timestamp
on write and breaking out of the ratelimiting loop when the token
bucket is empty.
> fix: incorrect latency measurements when ratelimited

- src/main.rs
- src/stats/mod.rs
The program fails to run with short intervals (< 10s) due to an
issue calculating the resolution of the heatmap summaries.
Change the resolution calculation to operate in floating point and
take the ceiling of the result. This prevents a zero duration for
the heatmap resolution.
> bugfix: fails to run with short intervals

- src/client/mod.rs
- src/config/general.rs
- src/config/mod.rs
Problem
To test TLS session impact on a server side rpc-perf should be able to reconnect with and w/o TLS session cache
The current implementation does not use that feature of rusttls
Solution
Add option to control TLS number of cached sessions. 
Result
We can test TLS session impact
> add TLS session cache support

- .gitignore
- src/stats/snapshot.rs
**Problem**
There are 2 issues:
- Some prometheus metrics collectors (ex. [open telemetry](https://github.com/open-telemetry/opentelemetry-collector/issues/3118)) don't support untyped prometheus metrics. Per the [prometheus spec](https://prometheus.io/docs/instrumenting/exposition_formats/#line-format), an optional metric `TYPE` can be added to each metric. Open telemetry requires this to process metrics
- [Prometheus](https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels) requires metric names to match this regex `[a-zA-Z_:][a-zA-Z0-9_:]*`, so metrics such as `responses_latency_p99.99` are actually invalid due to the `.` Using open telemetry, it won't process any of the metrics if one of the metrics is of invalid format.
**Solution**
I have changed the metric format to …
> fix: prometheus metric naming and typing

- README.md
Sample output removed from README.md because there isn't a section for sample output
Problem
There isn't a section for sample output so the link should be removed
Solution
Remove Sample output link from README.md
> Remove Sample Output link

- src/replay.rs
Problem
Currently the rpc-replay binary doesn't produce any stats and only
indicates replay progress. Additionally, any session errors result in
replay terminating.
Solution
Adds basic stats based on rpc-perf stats. Close sessions which have
errors and continue replay with remaining sessions.
Result
More useful stats while replaying cache traces, better resilience when
encountering errors.
> replay: add basic stats and error handling

- src/client/mod.rs
- src/config/general.rs
Problem
TLSConfig has default session size [32](https://docs.rs/rustls/0.18.1/src/rustls/client/mod.rs.html#164).
Current code implementation left default cache on even if provided option says 0.
But the expectation is when the cache size option is 0 the expectation is to avoid caching at all.
Solution
Turn off cache when the cache size is 0
Result
session cache size 0 turns off caching completely
> TLSCache: turn off if cache size is 0

- Cargo.lock
- Cargo.toml
- src/admin.rs
- src/codec/echo.rs
- src/codec/memcache.rs
- src/lib.rs
- src/metrics.rs
- src/replay.rs
- src/session.rs
- src/worker.rs
We're looking to deprecate `rustcommon-fastmetrics` along with `rustcommon-metrics` and centralize on `rustcommon-metrics-v2` which avoids some of their downsides.
This PR replaces all uses of `rustcommon-fastmetrics` with equivalent uses of `rustcommon-metrics-v2`-style metrics. 
One thing to note is that I've gone ahead and merged the duplicated definitions of `Admin` and `Snapshot` between `replay` and the main library. They were mostly identical so it only was necessary to add a few match statements around working with the config.
> Convert metrics to use `rustcommon-metrics-v2`

- .github/workflows/cargo.yml
Currently, we're still working with a pre-release branch for 4.0.0
and should have CI enabled for PRs against that branch.
Changes the CI config to enable runs on PRs against any branch.
> ci: enable CI runs for PRs against any branch

- src/admin.rs
Percentiles are expressed as 0.0-100.0, not 0-1
> fix: percentiles in rpc-perf / rpc-replay

- src/replay.rs
Currently, rpc-replay only allows speeds relative to the original cache trace. This PR adds a way to specify a request rate to apply a more constant load which doesn't have the varying request rates present in the trace. Aspects of the workload which are not dependent on timing are preserved (request mix, key distrubution, etc). 
This is useful in testing where we want to replay a cache-trace near instance red-line throughput.
> rpc-replay: add ratelimit based playback

- src/admin.rs
- src/lib.rs
Adds an admin endpoint to adjust the reconnect ratelimit at
runtime.
> add support for adjustable reconnect ratelimit

- configs/memcache.toml
- src/codec/memcache.rs
- src/config.rs
- src/config_file.rs
Adds the ability to specify a batch_size for a keyspace and send
multiple keys in the same memcache GET request.
> memcache: add support for batch_size for GET requests

- src/admin.rs
Adds type annotations to the prometheus exposition format so that
this is compatible with opentelemetry collector. Adjusts some of
the formatting for metric names
> opentelemetry type annotations

- configs/memcache.toml
- configs/memcache_zookeeper.toml
- configs/pelikan.toml
- configs/ping.toml
- configs/thrift_cache_hash.toml
- configs/thrift_cache_list.toml
- src/codec/mod.rs
- src/codec/redis.rs
- src/codec/thrift.rs
- src/codec/thrift_cache.rs
- src/config_file.rs
- src/worker.rs
Adds `ThriftCache` protocol support to the 4.x branch. Defines additional commands that are supported by the protocol.
Include more comments in the example configs.
> codec: add thrift cache support to 4.x

- .github/workflows/cargo.yml
- configs/memcache.toml
- configs/memcache_zookeeper.toml
- configs/pelikan.toml
- configs/redis.toml
- configs/redis_resp.toml
- configs/thrift_cache_hash.toml
- src/codec/memcache.rs
- src/codec/redis.rs
Problem
Redis coded fails to consume response bytes for numeric response.
This results in buffer corruption and connection churn.
Solution
Consume the response bytes for numeric response.
Result
Smoketests show no connection churn in CI.
> fix redis response handling

- .github/workflows/cargo.yml
Disable cargo audit, as it is expected to fail with the current
time libraries
> ci: disable cargo audit

- README.md
Updates the usage instructions in the readme to reflect the config
file as the only way to configure rpc-perf
> docs: update usage instructions in readme

- Cargo.lock
- Cargo.toml
Updates the cargo manifest to pin the rustcommon version to a
specific SHA. This prevents unintentionally pulling-in any
breaking changes.
> pin rustcommon version by SHA

- src/admin.rs
PR #363 added metrics descriptions, but mistakenly iterates through
the counters twice for prometheus/opentelemetry format and
incorrectly reports each counter as both a counter and a gauge.
Fixes a bad copy-paste from that PR.
> fix: fix issue introduced in #363

- src/codec/thrift_cache.rs
Fixes a bug in the thrift cache protocol where bytes were not
consumed from the buffer after receiving a response. This leads to
subsequent requests getting stuck in the incomplete response state.
Changes the decode logic to consume the bytes to fix the bug.
> fix: thrift cache protocol

- configs/memcache.toml
- configs/memcache_zookeeper.toml
- configs/pelikan.toml
- configs/redis.toml
- configs/redis_resp.toml
- configs/thrift_cache_hash.toml
- configs/thrift_cache_list.toml
- src/config.rs
- src/config_file.rs
The cardinality of the keyspace being constant (in the case of the U32 field type) or tied directly to the 52^N of the keyspace length (in the case of the Alphanumeric field type) makes it difficult to control the exact size of the keyspace:
len1: 52
len2: 2,704
len3: 140,608
len4: 7,311,616
len5: 380,204,032
len6: 19,770,609,664
The wide gaps between these keyspace cardinalities make it difficult to design load test configurations that achieve a specific hit-rate.
This PR implements the "cardinality" config option for key/innerkey/value spaces for U32 field types which constrains the range of the random number generator used to generate these fields.
See above.
It's worth noting that serde only seems to want to accept functions for defaults, and not literals, so I used u32.max_value() …
> Add cardinality to U32 key/value configs
